name: pihole

services:
  pihole:
    image: pihole/pihole:2026.07.2
    container_name: pihole
    hostname: pihole

    environment:
      TZ: Europe/Zurich

      # Mot de passe Web fourni par Docker Secret.
      WEBPASSWORD_FILE: pihole_webpasswd

      # Pi-hole reçoit des requêtes depuis le LAN et le réseau OpenVPN.
      FTLCONF_dns_listeningMode: "ALL"

      # DNS upstream actuels.
      FTLCONF_dns_upstreams: "${UPSTREAM_DNS_1};${UPSTREAM_DNS_2}"

      # DNS local Einstein.
      FTLCONF_dns_hosts: |-
        10.8.0.1 einstein.chantevigne.com

      # Pi-hole ne fournit pas le service NTP.
      FTLCONF_ntp_ipv4_active: "false"
      FTLCONF_ntp_ipv6_active: "false"

    volumes:
      - /volume1/docker/einstein/data/pihole:/etc/pihole

    secrets:
      - pihole_webpasswd

    networks:
      pihole_lan:
        ipv4_address: "${PIHOLE_IP}"

      pihole_vpn:
        ipv4_address: "${PIHOLE_VPN_IP}"

    mem_limit: 512m
    cpu_shares: 256

    restart: unless-stopped

    logging:
      driver: local
      options:
        max-size: 10m
        max-file: "3"

secrets:
  pihole_webpasswd:
    file: /volume1/docker/einstein/secrets/pihole_webpasswd.txt

networks:
  pihole_lan:
    driver: macvlan

    driver_opts:
      parent: "${PIHOLE_PARENT}"
      macvlan_mode: bridge

    ipam:
      config:
        - subnet: "${LAN_SUBNET}"
          gateway: "${LAN_GATEWAY}"

  pihole_vpn:
    driver: bridge

    ipam:
      config:
        - subnet: "${PIHOLE_VPN_SUBNET}"

